### ISSUE TITLE
error: data matches more than one schema in oneOf(<response-type>)

### ISSUE THREAD

**Issue by tim-koehler** [okta/okta-sdk-golang#549]
### Describe the bug?

I am facing this error on multiple endpoints with the new sdk v6.

For example:
- data matches more than one schema in oneOf(ListGroupAssignedRoles200ResponseInner)
- data matches more than one schema in oneOf(ListJwk200ResponseInner)

There are most like more existing.

### What is expected to happen?

No error and the proper response data should be returned.

### What is the actual behavior?

error with the message: `data matches more than one schema in oneOf(<response-type>)`

### Reproduction Steps?

````go
client := okta.NewAPIClient(cfg)

roleAssignedUsers, _, err := client.RoleAssignmentAUserAPI.ListUsersWithRoleAssignments(context.Background()).Execute()
if err != nil {
	panic(fmt.Errorf("failed to list users with role assignments: %w", err))
}

for _, user := range roleAssignedUsers.Value {
	rolesResponse, _, err := client.RoleAssignmentAUserAPI.ListAssignedRolesForUser(context.Background(), *user.Id).Execute()
	if err != nil {
		panic(fmt.Errorf("failed to list assigned roles for user %s: %w", *user.Id, err))
	}

	for _, role := range rolesResponse {
		fmt.Printf("User: %s, Role: %s\n", *user.Id, *role.StandardRole.Label)
	}
}
````

In this case there are 4 users with the "Super Administrator" role on the targeted tenant.

### Golang Version

go version go1.25.3 darwin/arm64

### SDK Version

v6.0

**Comment by tim-koehler** [comment]
@pranav-okta 
I am having this issue with  a lot of endpoints:
`failed to unmarshal ListApplications200ResponseInner as OpenIdConnectApplication: data matches more than one schema in oneOf(ListJwk200ResponseInner)`

```go
result, _, err := client.ApplicationAPI.ListApplications(context.Background()).Execute()
if err != nil {
	fmt.Println(err)
	return
}
```

As of right now v6 is completely broken and unusable to me 😔

**Comment by pranav-okta** [comment]
@tim-koehler 
This could be a bug. Can you check what the `result` is?

**Comment by tim-koehler** [comment]
@pranav-okta I have just checked.

The `result` slice does contain some data. However, it only contains the default application like "Okta Admin Console", "Okta Dashboard" or "Okta Browser Plugin". None of our added applications are included.

**Comment by efi-valkyrie** [comment]
Encountered exactly the same issue with Roles (list custom roles, users roles assignment etc.) and Apps (list apps) related APIs (maybe others as well).
SDK return an error that seems to happen from the SDK not able to properly map the results to a go object.
The SDK also return the raw API response object which actually contain a success (status code 200 / 204) from API.

**Comment by pranav-okta** [comment]
This SDK is generated from the OpenAPI spec. Therefore, the issue may be related to the `oneOf` schema property used by the spec for these endpoints.

I'll take a look at this.

**Comment by pranav-okta** [comment]
I did some debugging and found that the OpenAPI spec used to generate the SDK is **missing discriminator properties** for endpoints that use `oneOf` schemas in their responses. 

A few of them are `StandardRole - CustomRole` (that affects all role assignment endpoints), `OAuthJWK` endpoints, and a few more.

**Comment by ohookins** [comment]
Have also experienced this here: https://github.com/okta/terraform-provider-okta/issues/2577 in the context of querying an OAuth App (`okta_app_oauth` resource in Terraform).

In this particular case, one of the structs is a subset of the other, so if the larger struct unmarshals successfully then the other one will.

**Comment by pranav-okta** [comment]
Hey, this has been fixed in the latest release `v6.0.1` SDK. We will be working on incorporating this into Terraform.

**Comment by tim-koehler** [comment]
@pranav-okta I have upgraded to v6.0.1 but I still see similar issues:

For example here: 
```
clientV6.ApplicationAPI.ListApplications(ctx).After(page).Execute()

failed to unmarshal ListApplications200ResponseInner as SamlApplication: no value given for required property allowMultipleAcsEndpoints"
```

Or here:
```
clientV6.IdentityProviderAPI.ListIdentityProviders(ctx).After(page).Execute()

data matches more than one schema in oneOf(IdentityProviderProtocol)
```

Recently it is really frustrating to work with the sdk and the terraform provider 😔

**Comment by pranav-okta** [comment]
I understand that the latest version of the SDK has some bugs. The reason is that the SDK was not updated for a long time and couldn't keep up with the latest API changes. We are trying to get both teams on the same page to avoid such issues. 

Please bear with us for a while. In the meantime, continue raising issues, and we'll try to fix them ASAP. 🙏

**Comment by pranav-okta** [comment]
@tim-koehler Could you create a new issue for this? I'm already working on the `IdP` issue, and we can track it in the new issue.
